"""Idempotent .env wizard. Never overwrites values that are already set."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Mapping, Optional

from zen.auth.credentials import DEFAULT_GITHUB_MCP_URL, HttpClient, check_github_token

TEMPLATE_VERSION = "1.0"
ENGINE_MODES = ("product", "persona", "investment")

TEMPLATE_KEYS = (
    "GITHUB_TOKEN",
    "GITHUB_USERNAME",
    "GITHUB_EMAIL",
    "GITHUB_ORG",
    "OPENROUTER_API_KEY",
    "ZEN_ENGINE_MODE",
    "GITHUB_MCP_URL",
    "GITHUB_OAUTH_CLIENT_ID",
)

DEFAULTS = {
    "ZEN_ENGINE_MODE": "product",
    "GITHUB_MCP_URL": DEFAULT_GITHUB_MCP_URL,
}


class WizardError(RuntimeError):
    """Raised when a supplied credential fails validation."""


def load_env_map(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def missing_keys(current: Mapping[str, str]) -> list[str]:
    missing: list[str] = []
    for key in TEMPLATE_KEYS:
        value = str(current.get(key, "")).strip()
        if not value:
            missing.append(key)
    return missing


def apply_env_updates(
    path: Path,
    updates: Mapping[str, str],
    *,
    overwrite: bool = False,
) -> list[str]:
    current = load_env_map(path)
    written: list[str] = []
    merged = dict(current)
    for key, value in updates.items():
        if not str(value).strip():
            continue
        if key in current and str(current[key]).strip() and not overwrite:
            continue
        merged[key] = str(value).strip()
        written.append(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# zenOS env template v{TEMPLATE_VERSION}",
        "# Generated by scripts/setup_env.py — do not commit this file.",
        "",
    ]
    for key in TEMPLATE_KEYS:
        if key in merged:
            lines.append(f"{key}={merged[key]}")
        elif key in DEFAULTS:
            lines.append(f"{key}={DEFAULTS[key]}")
    leftover = [k for k in merged if k not in TEMPLATE_KEYS]
    if leftover:
        lines.append("")
        lines.append("# extra keys preserved")
        for key in leftover:
            lines.append(f"{key}={merged[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return written


def run_wizard(
    *,
    env_path: Path,
    answers: Optional[Mapping[str, str]] = None,
    http: Optional[HttpClient] = None,
    interactive: bool = True,
    stream=None,
) -> dict[str, list[str]]:
    out = stream or sys.stdout
    current = load_env_map(env_path)
    supplied = {k: v for k, v in dict(answers or {}).items() if str(v).strip()}
    to_fill = missing_keys(current)
    skipped = [k for k in TEMPLATE_KEYS if k not in to_fill]
    collected: dict[str, str] = {}

    for key in to_fill:
        if key in supplied:
            collected[key] = supplied[key]
            continue
        if not interactive:
            if key in DEFAULTS:
                collected[key] = DEFAULTS[key]
            continue
        prompt = f"{key}"
        if key in DEFAULTS:
            prompt += f" [{DEFAULTS[key]}]"
        try:
            value = input(f"{prompt}: ").strip()
        except EOFError:
            value = ""
        if not value and key in DEFAULTS:
            value = DEFAULTS[key]
        if value:
            collected[key] = value

    token = collected.get("GITHUB_TOKEN") or current.get("GITHUB_TOKEN", "")
    if token.strip() and "GITHUB_TOKEN" in collected:
        status = check_github_token(token, validate=True, http=http)
        if status.status != "ok":
            raise WizardError(status.message or "invalid GitHub token")

    written = apply_env_updates(env_path, collected, overwrite=False)
    print(f"Wrote {env_path} (mode 600 if supported).", file=out)
    print(f"Set: {', '.join(written) or '(none)'}", file=out)
    print(f"Skipped existing: {', '.join(skipped) or '(none)'}", file=out)
    return {"set": written, "skipped": skipped}


def main(argv: Optional[list[str]] = None) -> int:
    from pathlib import Path as P

    args = list(sys.argv[1:] if argv is None else argv)
    root = P.cwd()
    env_path = root / ".env"
    interactive = "--unattended" not in args
    answers = {k: v for k, v in __import__("os").environ.items() if k in TEMPLATE_KEYS}
    try:
        run_wizard(env_path=env_path, answers=answers, interactive=interactive)
    except WizardError as exc:
        print(f"Wizard aborted: {exc}", file=sys.stderr)
        return 10
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
